Faveod/ruby-tree-sitter

ext/tree_sitter/node.c
ext/tree_sitter/tree_sitter.h

Still waiting for a confirmation [from tree-sitter devs](https://github.com/tree-sitter/tree-sitter/discussions/1814) on whether this is a bug in their code or in the parser we're using and which produces child_count > 0 for `end` nodes, or maybe simply we're misusing the library.
Until then, and until someone complains, this will be default behavior.

node: make child_count return 0 on `end` nodes

---

ext/tree_sitter/node.c
ext/tree_sitter/parser.c
ext/tree_sitter/tree.c

`free(NULL)` should work on POSIX without any guards.
See https://pubs.opengroup.org/onlinepubs/009604499/functions/free.html
But for some reason this fixes a SEGFAULT we were having on calls to `node_string. 
It's most likely that someone is redefining `free` somewhere.
The other guards on `free` are just defensive guards. Better safe than on `gdb`.

Fix SEGFAULT on Node::inspect (node_string in C)

---

README.md
docs/SIGSEGV.md
examples/01-json.rb
examples/02-multilang.rb
examples/03-query.rb
examples/04-tree-cursor.rb
examples/05-segfault.rb
examples/helpers.rb
ext/tree_sitter/node.c
ext/tree_sitter/tree.c
ext/tree_sitter/tree_sitter.h
lib/tree_sitter.rb
test/tree_sitter/language_test.rb
test/tree_sitter/logger_test.rb
test/tree_sitter/node_test.rb
test/tree_sitter/parser_test.rb
test/tree_sitter/query_test.rb
test/tree_sitter/tree_cursor_test.rb
test/tree_sitter/tree_test.rb

This PR addresses some SEGFAULTs that can arise from using tree-sitter in forked processes.
The details are in `docs/SIGSEGV.md`.
TL;DR:
1. An exception involving a `node` is raised in a forked process.
2. `ruby` makes the exception string, but doesn't evaluate it.
3. When the fork terminates, there's a high chance that the `Tree` referenced by `Node` was Garbage Collected.
4. Calling any method on `node` will lead to a `SIGSEGV`.
To overcome this, I created a class variable `Tree::@@rc` that maps a `TSTree` pointer to a reference-count:
1. Whenever a `Tree` is created, its `rc` is set to 1.
2. Whenever a `Node` is created, its associated `Tree`'s `rc` is incremented.
3. Whenever a `Node` is `GC`ed, its associated `Tree`'s `rc` is decremented.
4. Whenever a `rc` hits `0`, `ts_tree_delete` …

Add reference-counting for Tree

---

ext/tree_sitter/node.c
ext/tree_sitter/tree.c

ruby 3.2 introduced a new warning when `rb_define_alloc_func` is not used. e.g.:
warning: undefining the allocator of T_DATA class TreeSitter::Tree
When we don't allocate a class, we need to undefine it manually using `rb_undef_alloc_func`.

c api: fix allocation warning

---

lib/tree_sitter/node.rb
test/tree_sitter/language_test.rb
test/tree_sitter/logger_test.rb
test/tree_sitter/node_test.rb
test/tree_sitter/parser_test.rb
test/tree_sitter/query_test.rb
test/tree_sitter/tree_cursor_test.rb

This PR is created specifically for a recurrent failure on ruby 2.7+macOS.
It seems like some race condition is happening with minitest, screwing $stderr.
We need this test because logging defaults to $stderr (by us, not tree-sitter), and we want to make sure that this invariant holds at all times.

Minor corrections in tests

---

.github/workflows/publish.yml
bin/publish

Follow-up to #18. This PR doesn't change how the artifacts are built but instead adds a new Github Action to publish the artifacts when a new release is published.
I tested this PR against a copy of this repo here: https://github.com/DerekStride/test-rb-ts-bindings
The logs for the new workflow are here: https://github.com/DerekStride/test-rb-ts-bindings/actions/runs/3877336119/jobs/6612235477
It fails because I never set the RubyGems API Key, instructions on how to do that are below.
```
Running gem release task...
+ release_command=bin/publish
+ exec bin/publish
Publishing pkg/tree_sitter-0.20.6.1-mri-2.7.gem
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up
---
error: Invalid credentials
code: 401
```
I used the [Fetch Github …

Publish gem artifacts on release

---

bin/publish

fixes https://github.com/Faveod/ruby-tree-sitter/issues/23#issuecomment-1426757155
The [failed publish build](https://github.com/Faveod/ruby-tree-sitter/actions/runs/4151349566/jobs/7181605454) was a result of attempting to publish equivalent gem packages. Digging in a bit there were two successful pushes then a failure.
**Success 1**
```
Publishing pkg/ruby_tree_sitter-0.20.6.3-mri-2.7.gem
Pushing gem to https://rubygems.org.../
Successfully registered gem: ruby_tree_sitter (0.20.6.3)
```
**Success 2**
```
Publishing pkg/ruby_tree_sitter-0.20.6.3-x86_64-darwin-19-mri-2.7.gem
Pushing gem to https://rubygems.org.../
Successfully registered gem: ruby_tree_sitter (0.20.6.3-x86_64-darwin-19)
```
**Failure**
```
Publishing pkg/ruby_tree_sitter-0.20.6.3-mri-3.gem
Pushing gem to …
```

Only publish unique gem versions

---

ext/tree_sitter/tree.c

RARRAY_PTR is bad for GC performance as it exposes the internal buffer of the array meaning that the array becomes write barrier unprotected.

Remove usage of RARRAY_PTR

---

tree_sitter.gemspec

The `ext/tree_sitter/repo.rb` file isn't included in the files packaged with the gem.
```
extconf.rb:6:in `require_relative': cannot load such file --
/home/runner/work/tree_stand/tree_stand/vendor/bundle/ruby/3.1.0/gems/ruby_tree_sitter-0.20.8.2/ext/tree_sitter/repo
```
ref: https://github.com/Shopify/tree_stand/actions/runs/7173716654/job/19533672716
The fix is fairly simple:
```
>> Dir.glob('ext/**/*.{c,h,rb}') - Dir.glob('ext/**/*.[ch]')                                                                                                                                                                              
=> ["ext/tree_sitter/repo.rb", "ext/tree_sitter/extconf.rb"]
```

fix(gem): include `repo.rb` in gemspec files

---

.github/workflows/ci.yml

3.1 parsers have their versions fixed in a ref file + they're bumped to more modern versions.

ci: bump disable-sys-libs parsers to 3.1

---

lib/tree_stand/utils/printer.rb

```error
lib/tree_stand/utils/printer.rb:37:in `*': negative argument (ArgumentError)
io << "#{line.sexpr}#{' ' * (@ralign - line.sexpr.size)}| #{line.text}\n"
^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
We append closing parenthesis to close the last open node recursively. This can sometimes cause an overflow where `Line#sexpr` returns a string longer than the right aligned node text column.
https://github.com/Faveod/ruby-tree-sitter/blob/bae141002843e56544279b772dfd4775b92f6262/lib/tree_stand/utils/printer.rb#L68
This change makes sure that in those edge cases we don't raise an argument error.

fix(pretty-print): never pad by less than zero

---

.clang-format
ext/tree_sitter/node.c
lib/tree_sitter/node.rb
test/tree_sitter/node_test.rb

This PR contains:
1. An improvement on `Node#field?`, accepting strings and symbols.
2. Fixing segfaults on calls to `Node#child_by_filed_name`, returning `nil` when the field name does not exist, also accepting strings and symbols.
3. Improvements on tests.

Fix Segfault bug on `child_by_field_name`

---

.rubocop.yml
.yardopts
README.md
bin/setup
ext/tree_sitter/language.c
ext/tree_sitter/logger.c
ext/tree_sitter/parser.c
lib/tree_stand/config.rb
lib/tree_stand/parser.rb
test/test_helper.rb
test/tree_stand/parser_setup_test.rb

This PR contains:
1. Release of TreeSitter documentation
2. Correction of Node#pretty_print signatures (sorbet)
3. A change in the default printing device, of `TreeStand::Utils::Printer` from a `StringIO` created each time we call `pretty_print`, to something fixed in the printer class, and configurable as well, through `TreeStand.config.io`.
4. Add some sane defaults to load parsers automagically if no config is provided.
@DerekStride I did these changes while working with TreeStand, and I acknowledge the fact they could be broken into different PRs, but I just did them in a single one for convenience.
I would love to have your feedback, as I did some things on the spot and I might be missing something.

TreeSand load improvement

---

News.md
bin/check
lib/tree_sitter/node.rb
lib/tree_sitter/query_captures.rb
lib/tree_sitter/query_matches.rb
lib/tree_stand/node.rb
test/tree_sitter/node_test.rb
test/tree_sitter/query_test.rb
test/tree_stand/node_test.rb

- `TreeSitter::Node` is enumerable.
- `TreeSitter::{QueryCaptures, QueryMatches}` are enumerable.
- `TreeStand::Node` now supports query predicates from `TreeSitter`.
- `TreeSitter::QueryMatches` now has a `collect` method returning an `Array<Hash<String, Node>>`,
the equivalent of what `TreeStand::Node#query` returns.

Make `TreeSitter::{QueryMatches, QueryCaptures}` enumerable and support predicates in `TreeStand`

---

.github/workflows/ci.yml
Gemfile
News.md
Rakefile
bin/publish
lib/tree_sitter/version.rb

I'm either missing on something in the docs of rake-compiler and
rake-compiler-dock, or the doc is missing some crucial information.
Trying to read the existing repos is not helping that much neither
(especially Nokogiri).
If I find the opportunity to spend all the time necessary to fix this, I
would gladly spend it. If someone else would like to contribute, it will
be even better, because I don't think it's possible in the near future.

Disable native gem / cross-compilation

---

.justfile
lib/tree_sitter/mixins/language.rb

This is mostly relevant to times where you need to load `COBOL` for example. Now we can just say `TreeSitter.load('COBOL')`, and that will be enough to load correctly the symbol 'COBOL' from the compiler parser, and at the same capable of looking up parsers
`cobol.so/COBOL.so/tree-sitter-cobol.so/tree-sitter-COBOL.so/…`.

mixin: lang: be more leniant in language loading.

---

News.md
Rakefile
ext/tree_sitter/extconf.rb
ext/tree_sitter/repo.rb
patches/cross-compile.patch

Macos targets didn't compile because the makefile of tree-sitter didn't work in cross-compilation environments.
My last patch was obviously wrong: https://github.com/tree-sitter/tree-sitter/pull/1824
I checked the new way with this test-suite and it's good.

Cross compile: patch macos target

---

bin/publish
lib/tree_sitter/version.rb

And publish all cross-compiled gems. See https://github.com/Faveod/ruby-tree-sitter/pull/70.

Bump to v1.6.0

---

.github/workflows/bump-tree-sitter.yml
.gitignore
bin/ci-push-gems
bin/ci-test-project
docker/base.dockerfile
docs/Maintaining.md

This will make it easier for us to frequently release new gems for new tree-sitter versions.
I will merge once the scheduled release passes. I tested on my local fork and it works.

ci: automatically bump tree-sitter on new releases

---

News.md
ext/tree_sitter/language.c
ext/tree_sitter/query.c
lib/tree_sitter.rb
lib/tree_sitter/error.rb
lib/tree_sitter/mixins/language.rb
test/tree_sitter/language_test.rb
test/tree_sitter/query_test.rb

Raising `RuntimeError` on its own, everywhere, was not a good idea, but it was handy when I was learning how to write extensions, and I wanted to move as fast as possible.
All the added errors are now `< TreeSitterError < StandardError`, which gives the user more control on what to catch, when, and what to do when encountered.

Add custom errors

---

.rubocop.yml
News.md
lib/tree_sitter/error.rb
lib/tree_sitter/version.rb

We don't want our exceptions to go unnoticed or handled by default `rescue`.
Consumers need to handle them explicitly.

Make TreeSitterError inherit Exception

---

.justfile
News.md
Rakefile
lib/tree_sitter/version.rb

Rake-compiler-dock just silently removed support for `3.3.0` in the version strings, instead of exploding.
See [here](https://github.com/rake-compiler/rake-compiler-dock/blob/3811c31917a9dcb9cb139c0841f420c82663ae89/History.md?plain=1#L35).

FIx cross-compiled for Ruby 3.3 & Bump v1.11.1
